version: '2'
.catalog:
  name: Wordpress
  version: 0.0.1-wordpress-rancher
  description: |
    O sistema de gerenciamento de conteúdo rico do WordPress pode utilizar plugins, widgets e temas.
  minimum_rancher_version: v0.56.0
  maintainer: "Marcelo Bomfim"

services:

    wordpress:
        scale: 1
    db:
        scale: 1
