version: '2'
services:
  gitlab-server:
    ports:
      - ${ssh_port}:22/tcp
      - ${http_port}:80/tcp
      - ${https_port}:443/tcp
    labels:
      io.rancher.container.hostname_override: container_name
    image: gitlab/gitlab-ce:10.1.3-ce.0
    volumes:
      - ${GITLAB_DATA}:/var/opt/gitlab:rw
      - ${GITLAB_LOG}:/var/log/gitlab:rw
      - ${GITLAB_CONF}:/etc/gitlab:rw
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${gitlab_omnipus_prefix}${gitlab_hostname}'
        registry_external_url '${gitlab_omnipus_prefix}${registry_gitlab_hostname}'
        gitlab_rails['gitlab_shell_ssh_port'] = ${ssh_port}
